name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5bd7f2ffea1c970f74e38f9decd83eef892bd0ef2189ad0b7232e8a51dc0843"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
