name = "WarpDrive"
filename = "WarpDrive-1.12.2-1.5.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3308/55/WarpDrive-1.12.2-1.5.22.jar"
hash-format = "murmur2"
hash = "168099796"

[update]
[update.curseforge]
file-id = 3308055
project-id = 233565
release-channel = "beta"
